name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node
        uses: actions/setup-node@v4

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Install
        run: pnpm i

      - name: PNPM build
        run: pnpm build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
